services:
  postgres:
    image: postgres:15
    container_name: postgres_estadisticas
    environment:
      POSTGRES_DB: estadisticasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  microservicio_estadisticas:
    build: .
    container_name: microservicio_estadisticas
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/estadisticasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVICE_CONTENIDO_URL: http://host.docker.internal:8081/
      SENTRY_AUTO_INIT: false
    ports:
      - "8083:8083"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: